# Licensed to the Apache Software Foundation (ASF) under one or more
# license agreements; and to You under the Apache License, version 2.0:
#
#   https://www.apache.org/licenses/LICENSE-2.0
#
# This file is part of the Apache Pekko project, which was derived from Akka.
#

name: Link Validator

permissions: {}

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * 1'

jobs:
  validate-links:
    runs-on: ubuntu-22.04
    if: github.repository == 'apache/pekko-persistence-cassandra'
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Checkout GitHub merge
        if: github.event.pull_request
        run: |-
          git fetch origin pull/${{ github.event.pull_request.number }}/merge:scratch
          git checkout scratch

      - name: Setup Java 8
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4.7.1
        with:
          distribution: temurin
          java-version: 8

      - name: Cache Coursier cache
        uses: coursier/cache-action@4e2615869d13561d626ed48655e1a39e5b192b3c # v6.4.7

      - name: Setup Coursier
        uses: coursier/setup-action@039f736548afa5411c1382f40a5bd9c2d30e0383 # v1.3.9

      # assign an arbitrary version number so that scripts/link-validator.conf has a predictable set of links to work with
      - name: Create the Pekko site
        run: sbt "set ThisBuild / version := \"1.0.0\"; unidoc; docs/paradox"

      - name: Run Link Validator
        run: cs launch net.runne::site-link-validator:0.2.2 -- scripts/link-validator.conf
